### ISSUE TITLE
加了个锁，

### ISSUE THREAD

**Issue by ydf0509** [GoodManWEN/ThreadPoolExecutorPlus#1]
1、修改的 https://github.com/ydf0509/distributed_framework/tree/master/function_scheduling_distributed_framework/concurrent_pool

那就加个锁吧，改后的的放在另一个项目的并发池文件夹里面，threadppoolexecutor_shrink_able的152行。  

with self._executorx._lock_compute_threads_free_count:
                    if self._executorx.threads_free_count > self._executorx._min_workers:
                        self._remove_thread(f'当前线程超过60秒没有任务，线程池中不在工作状态中的线程数量是 {self._executorx.threads_free_count}，超过了指定的数量 {self._executorx._min_workers}')
                        break   # 退出while 1，即是结束。这里才是决定线程结束销毁，_remove_thread只是个名字而已，不是由那个来销毁线程。
                    else:
                        continue

2、那你对实现asyncio的协程池，维护一个concurent.futures相同api有什么看法。

3、你的池采用simple_queue没指定大小，那么当你主线程从redis或者mq取任务，然后submit到子线程运行任务，你会发现redis的数十万任务在十几秒内迅速掏空，被添加到你的无底洞simplequeue了。此时另一台分布式机器再启动代码后，无法从redis取任务了。而且你把redis任务都取到simpleque暂存后，当你停止代码时候，内存中数十万任务瞬间丢失，最好用有界队列。

**Comment by GoodManWEN** [comment]
1、你没有理解问题产生的原因。问题产生的原因不在于锁，而在于timeout抛出异常后不是原子操作，此时如果发生线程切换，统计计数没有更新，与是否加锁、执行逻辑是否抛出异常全都无关。解决方案引用我在刚才写的，目前基本是无法解决。合理的解决方式是hack进queue的实现，在抛出异常前更新计数。翻了翻，SimpleQueue 引用自 DLLS\_queue.pyd ，其来自于源码包里的 _queuemodule.c.h 和 _queuemodule.c， 如果用纯 python 实现的话，关键的计时唤醒功能来自 threading.Semaphore() , 里面的实现调用的內建库 _thread， 这个库没有__file__属性，找不到源码，具体细节就涉及 python 本身编译了，以前没搞过，看不懂了。

解决方案是其一同步传入锁和计数，在dll内部完成加锁和更新，再抛出异常，同时读取时加锁。两种hack方案分别需要修改_queuemodule.c 和 _thread，成本太高，所以目前能做的只能是增大最小池容量，理论上更大的最小容量会降低线程全部占用导致阻塞的几率。

3、使用场景不同，我觉得业务逻辑引入库解决是没有任何意义。

**Comment by ydf0509** [comment]
你自己试试
`
while  1：
     msg = redis.lpop('listkey' )
     pool.submit(func,msg)
`
就知道了，瞬间几十万任务从redis取出来了

**Comment by ydf0509** [comment]
加909686719 q
